FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY "Lava.sln", "Lava.sln"
COPY ["Lava.Domain.csproj", "Lava.Domain/"]
COPY ["Lava.WebAPI.csproj", "Lava.WebAPI/"]
RUN dotnet restore "Lava.sln"

WORKDIR "/src/Lava.WebAPI"
COPY . .

RUN dotnet build "Lava.WebAPI.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Lava.WebAPI.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Lava.WebAPI.dll"]
