name: LavaWebApp CICD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  DOCKER_REGISTRY_URL: lavaacr.azurecr.io
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: ACR Login
        uses: Azure/docker-login@v1
        with:
          login-server:  ${{ env.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.LAVA_ACR_USERNAME }}
          password: ${{ secrets.LAVA_ACR_PASSWORD }}
        
      - name: Build and Push Docker Image
        run: | 
          docker build . -t ${{ env.DOCKER_REGISTRY_URL }}/lavawebapp:${{ github.run_id }}
          docker push ${{ env.DOCKER_REGISTRY_URL }}/lavawebapp:${{ github.run_id }}
          
      - name: Package ARM Template
        uses: actions/upload-artifact@v2
        with: 
          name: arm-templates
          path: ${{ github.workspace }}/Lava.WebApi/azuredeploy.json
          retention-days: 5
        
  dev: 
    runs-on: ubuntu-latest
    
    needs: build
    environment: development
    
    env:
      ENVIRONMENT_PREFIX: dev
      
      SERVER_FARM_RESOURCE_GROUP_NAME: DEV-ACRCD_RG
      WEBAPP_LOCATION: uksouth
      WEBAPP_SKU: Free
      WEBAPP_SKU_CODE: F1
      
      TAG_ENVIRONMENT: DEVELOPMENT
      
    steps:
    
      - name: Dowload ARM Templates
        uses: actions/download-artifact@v3
        with:
          name: arm-templates
          
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DEV_SP_CREDENTIALS }}
          
      - name: Deploy ARM Template
        uses: 
        
    
      
